### ISSUE TITLE
NumberFormatException when vnf-profile.id is not an integer

### ISSUE THREAD

**Issue by kostistr** [openslice/io.openslice.mano#12]
**Error log**

java.lang.NumberFormatException: For input string: "vnf",
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68),
	at java.base/java.lang.Integer.parseInt(Integer.java:658),
	at java.base/java.lang.Integer.parseInt(Integer.java:776),
	at io.openslice.mano.MANOController.mapOSM10NSD2Product(MANOController.java:3224),
	at io.openslice.mano.MANOController.mapOSM10NSD2ProductEagerDataJson(MANOController.java:3116)

**NSD yaml**

    df:
    - id: default-df
      vnf-profile:
      - id: vnf <-- string

**Comment by Ioannischatzis** [comment]
This issue affects NFV Portal Onboarding.

**Comment by kostistr** [comment]
[OSM_Export_hackfest_basic-ns-metrics.tar.gz](https://github.com/openslice/io.openslice.mano/files/12144693/OSM_Export_hackfest_basic-ns-metrics.tar.gz)
[OSM_Export_hackfest_basic_metrics-vnf.tar.gz](https://github.com/openslice/io.openslice.mano/files/12144695/OSM_Export_hackfest_basic_metrics-vnf.tar.gz)

This issue was reproduced with these artifacts. UI was ok when vnf-profile.id was changed to an integer (eg. 1) from 'vnf'.

**Comment by Ioannischatzis** [comment]
Closing this issue with commits
https://github.com/openslice/io.openslice.mano/commit/ca26f09f49fbd52e507be19a81cc727ffd437c6a
https://github.com/openslice/io.openslice.model/commit/6db8401e272a817e421482ad3d6a65e19b0392ee
